exports.sampleListOfProducts = [
    {
        product_name: "iphone 14 pro",
        product_id: "1",
        description: "The Apple iPhone 14 pro is overall a great phone for anyone who is looking for high speed, excellent camera quality, and a day-long of battery life.",
        list_price: 80000,
        sale_price: null,
        final_price: '80,000',
        in_store: 2,
        brand_name: "apple",
        category_name: "electronics",
        shop_seller_name: "Apple BKC",
        quantity_in_cart: 1
    },
    {
        product_name: "Nude Cusion Italy",
        product_id: "2",
        description: "The Apple iPhone 14 pro is overall a great phone for anyone who is looking for high speed, excellent camera quality, and a day-long of battery life.",
        list_price: 80000,
        sale_price: null,
        final_price: '1,000',
        // in_store: 0,
        brand_name: "Lakeme",
        category_name: "cosmetics",
        shop_seller_name: "lakeme beauty INC",
        // quantity_in_cart: 1
    },
    {
        product_name: "iphone 14 pro Max",
        product_id: "3",
        description: "The Apple iPhone 14 pro is overall a great phone for anyone who is looking for high speed, excellent camera quality, and a day-long of battery life.",
        list_price: 100000,
        sale_price: null,
        final_price: '1,00,000',
        in_store: 5,
        brand_name: "apple",
        category_name: "electronics",
        shop_seller_name: "Apple BKC",
        // quantity_in_cart: 1
    },
    {
        product_name: "iphone 14 pro",
        product_id: "4",
        description: "The Apple iPhone 14 pro is overall a great phone for anyone who is looking for high speed, excellent camera quality, and a day-long of battery life.",
        list_price: 80000,
        sale_price: null,
        final_price: '80,000',
        in_store: 2,
        brand_name: "apple",
        category_name: "electronics",
        shop_seller_name: "Apple BKC",
        quantity_in_cart: 1
    },
    {
        product_name: "Nude Cusion Italy",
        product_id: "5",
        description: "The Apple iPhone 14 pro is overall a great phone for anyone who is looking for high speed, excellent camera quality, and a day-long of battery life.",
        list_price: 80000,
        sale_price: null,
        final_price: '1,000',
        // in_store: 0,
        brand_name: "Lakeme",
        category_name: "cosmetics",
        shop_seller_name: "lakeme beauty INC",
        // quantity_in_cart: 1
    },
    {
        product_name: "iphone 14 pro Max",
        product_id: "6",
        description: "The Apple iPhone 14 pro is overall a great phone for anyone who is looking for high speed, excellent camera quality, and a day-long of battery life.",
        list_price: 100000,
        sale_price: null,
        final_price: '1,00,000',
        in_store: 5,
        brand_name: "apple",
        category_name: "electronics",
        shop_seller_name: "Apple BKC",
        // quantity_in_cart: 1
    },
]